### ISSUE TITLE
Documentation: PyMS with pipenv

### ISSUE THREAD

**Issue by avara1986** [python-microservices/pyms#162]
PyMS has extra arguments. You can add PyMS in your requirements like:

```
Flask-SQLAlchemy ==2.4.4
...
py-ms[all]==2.6.1
```

Explain in the docs how to integrate with pipenv like:

```toml
[packages]
Flask-SQLAlchemy = "==2.4.4"
...
py-ms = {extras = ["all"],version = "==2.6.1"}
```
