### ISSUE TITLE
Find a way to standarize the configuration file

### ISSUE THREAD

**Issue by alexppg** [python-microservices/pyms#75]
**Is your feature request related to a problem? Please describe.**
The configuration file has some quirks. With the given example:

```yaml
my-minimal-microservice:
  APP_NAME: "Python Microservice"
  environment: "I'm running in a local machine"
pyms:
  requests:
    data: ""
  metrics: true
```
- The `APP_NAME` and the `my-minimal-microservice` are redundant
- `APP_NAME` is expected to be in capital letters, but others don't.

**Describe the solution you'd like**
Something like:

```yaml
config:
  app_name: "Python Microservice"
  environment: "I'm running in a local machine"
pyms:
  requests:
    data: ""
  metrics: true
```
There should something that converts the app_name to an usable name, changing spaces by slashes or something like that.

Also, if using capital letters for keys of the configuration makes sense, it should be established somewhere which ones are and why.

**Describe alternatives you've considered**
NaN

**Additional context**
NaN
